# Generated by Django 3.2.9 on 2021-12-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=50)),
                ('debitCredit', models.CharField(max_length=15)),
                ('particular', models.CharField(max_length=300)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
