# Generated by Django 3.2.9 on 2021-12-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_ledger_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='username',
            field=models.CharField(max_length=256),
        ),
    ]
