# Generated by Django 3.2.6 on 2021-08-30 08:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='dateAdded',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
