# Generated by Django 3.2.6 on 2021-09-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_dateadded'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
